In [1]:
import numpy as np

list\
tuple\
dict\
set 

all are heterogeneous type.

<b>Why should we use numpy arrays:</b>

np.array(sequence)

np arrays are homogeneous


<b>Why numpy arrays faster than list:</b>

1. Locality of reference - things are store in numpy array in contineous blocks in the memory


## Creating a Numpy Array

In [2]:
a1 = np.array((1,2,3))

In [3]:
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a1.shape

(3,)

In [6]:
[[1,2],[2,4]]
a2 = np.array([[1,2],[2,4]])

In [7]:
a2

array([[1, 2],
       [2, 4]])

In [8]:
a2.shape

(2, 2)

In [9]:
a3=[[[1,2],[2,4]],
[[2,3],[1,4]],
[[4,2],[1,4]]]
a3=np.array(a3)

In [10]:
a3

array([[[1, 2],
        [2, 4]],

       [[2, 3],
        [1, 4]],

       [[4, 2],
        [1, 4]]])

In [11]:
a3.shape

(3, 2, 2)

## Data type

In [12]:
a4 = np.array((1,2,3),dtype='float64')

In [13]:
a4

array([1., 2., 3.])

In [14]:
a6 = np.array((1,2,3),dtype=np.float64)

In [15]:
a6

array([1., 2., 3.])

In [16]:
a5 = np.array((1,2,3),dtype='int8')

In [17]:
a5

array([1, 2, 3], dtype=int8)

## Numpy Arange

In [18]:
range(10)

range(0, 10)

In [19]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Different methods to create a numpy array

1. np.array()
2. np.arange()
3. np.ones()
4. np.zeroes()
5. np.linspace()
6. np.identity()
7. np.random.random()


In [21]:
np.arange(1,19).reshape(6,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [22]:
np.arange(1,19).reshape(3,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [23]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
np.ones((3,3,3),dtype='int')

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [25]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
np.random.random(10)

array([0.52589746, 0.63314199, 0.63368639, 0.71711187, 0.87959859,
       0.34968738, 0.07492636, 0.14635273, 0.89372747, 0.55445547])

In [27]:
np.random.random(10) * 100

array([68.58082083, 17.55351825, 11.97148835, 33.43889413, 42.27481594,
       94.49193346, 88.33940203, 93.7653484 ,  0.85742769, 36.11718546])

In [28]:
np.random.random((3,2,3))

array([[[0.86247131, 0.89205327, 0.48564168],
        [0.27760461, 0.96018508, 0.40670268]],

       [[0.32177449, 0.3350247 , 0.98674649],
        [0.13411714, 0.85533249, 0.30054896]],

       [[0.20770833, 0.013159  , 0.42376654],
        [0.31508629, 0.7293497 , 0.89358894]]])

In [29]:
np.random.random((3,2,3)) * 10

array([[[1.37475445, 6.45285285, 4.78990218],
        [0.8446326 , 8.57842607, 3.16847785]],

       [[3.54489029, 8.74413484, 3.50835507],
        [8.97584325, 3.69787885, 2.27873539]],

       [[1.51076152, 3.29611204, 5.93028026],
        [7.65981175, 3.22686966, 6.87321168]]])

In [30]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [31]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [32]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
a1.ndim

1

In [35]:
a2.ndim

2

In [36]:
a3.ndim

3

In [37]:
a1.size

3

In [38]:
a2.size

4

In [39]:
a2

array([[1, 2],
       [2, 4]])

In [44]:
a4.size

3

In [45]:
a4

array([1., 2., 3.])

In [50]:
np.arange(20).reshape(5,2,2).ndim

3

In [52]:
a7=np.arange(20).reshape(5,2,2)

In [57]:
a7.itemsize # 8 bytes

8

In [54]:
a7.size

20

In [55]:
a7

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [56]:
a7.dtype

dtype('int64')

## Changing Data Type

In [58]:
a7.astype('float')

array([[[ 0.,  1.],
        [ 2.,  3.]],

       [[ 4.,  5.],
        [ 6.,  7.]],

       [[ 8.,  9.],
        [10., 11.]],

       [[12., 13.],
        [14., 15.]],

       [[16., 17.],
        [18., 19.]]])

## Array Operations

1. indexing & slicing
2. Scaler Operation
 * addition,substraction,division,modulo,floor,relational operation,power

In [69]:
a8 = np.arange(1,76).reshape(3,5,5)

In [71]:
a8.size,a8.shape,a8.ndim,a8.itemsize

(75, (3, 5, 5), 3, 8)

In [72]:
a8

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]],

       [[26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45],
        [46, 47, 48, 49, 50]],

       [[51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60],
        [61, 62, 63, 64, 65],
        [66, 67, 68, 69, 70],
        [71, 72, 73, 74, 75]]])

In [73]:
a8[0]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [75]:
a8[0:3,0:3]

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40]],

       [[51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60],
        [61, 62, 63, 64, 65]]])

In [76]:
a1 

array([1, 2, 3])

In [77]:
a1 * 6

array([ 6, 12, 18])

In [78]:
a1 /3

array([0.33333333, 0.66666667, 1.        ])

In [79]:
a1 // 3

array([0, 0, 1])

In [80]:
a1 % 3

array([1, 2, 0])

In [84]:
a8[a8 >4 ]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75])

## Array Function

* sum(),min(),max(),prod(),mean(),median()

In [87]:
a9 = np.random.random(30) * 100000

In [89]:
a9

array([31084.91279238, 15522.81184889, 84034.15532176, 71550.18815042,
       77721.46661346, 35204.39899203, 94948.88447126, 72607.75774431,
       21226.47296489, 41162.60777726, 79962.00487351, 30875.52504917,
       61435.55644309, 68001.78676966, 61575.13217697,  3529.51839743,
        9528.51798704, 49680.89172118, 13463.18980719, 65651.27101889,
       86712.6883196 , 67838.03265719,  1576.14166888, 71460.32369309,
       64416.9562184 , 64892.04608319, 71805.62329411,   457.55434864,
       59708.78493086, 22956.66133122])

In [88]:
a9.max()

94948.88447125972

In [90]:
a9.min()

457.5543486354139

In [91]:
np.mean(a9)

50019.728782198654

In [92]:
np.median(a9)

61505.34431002876

In [93]:
np.sin(a9)

array([ 0.91133478, -0.2011654 ,  0.30178949, -0.40361533, -0.99938195,
       -0.28430755, -0.50527604, -0.66810977,  0.95468376,  0.99395979,
        0.81512115, -0.0475324 , -0.99003293, -0.90347561, -0.08373523,
       -0.99814319, -0.06741753, -0.25176414, -0.99443901, -0.98699371,
       -0.99982532, -0.99866427, -0.80628418,  0.99627   ,  0.98564344,
       -0.6379008 ,  0.98215639, -0.89930548, -0.31934979, -0.86432738])

In [94]:
np.cos(a9)

array([-0.41166603, -0.97955729, -0.95337459, -0.91492877,  0.03515273,
        0.95873313, -0.86295777,  0.74406273, -0.2976221 ,  0.1097449 ,
       -0.57929052,  0.9988697 ,  0.14083603,  0.4286395 ,  0.99648804,
       -0.06091115, -0.99772485,  0.96778862, -0.10531412, -0.1607589 ,
        0.01869046,  0.05166888,  0.59152838, -0.08629076, -0.16884021,
        0.77011854,  0.18806603,  0.437321  ,  0.94763691, -0.50292959])

In [96]:
a1 = np.arange(1,10).reshape(3,3)

In [97]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
# 0 -> column axis
# 1 -> row axis
np.max(a1,axis=0)

array([7, 8, 9])

In [99]:
np.max(a1,axis=1)

array([3, 6, 9])

## Dot Product

In [103]:
np.dot(np.arange(1,7).reshape(2,3),np.arange(7,13).reshape(3,2))

array([[ 58,  64],
       [139, 154]])

## Matrix Multiplication

* Matrix multiplication, often denoted as matmul, and dot product are fundamental operations in linear algebra.
* ![image](https://miro.medium.com/v2/resize:fit:720/format:webp/1*CjOmBjvCK4QpCSR0UABUXw.png)
* Matmul stands for matrix multiplication (including solving systems of linear equations, image processing, and deep learning)
* The dot product, also known as the inner product or scalar product, is a simpler operation that calculates the sum of the products of corresponding entries in two vectors.It’s widely used in geometry and physics, often for finding angles and projections.
* For large datasets or matrices, where computational efficiency is crucial, the dot product is often a faster option. It reduces the computational load while providing satisfactory results.
* ![image](https://miro.medium.com/v2/resize:fit:720/format:webp/1*c1KKlUpoiSOFjR038W1qwA.png)


In [61]:
import numpy as np

# Define two vectors for the dot product
vector_a = np.array([2, 3, 4])
vector_b = np.array([1, 5, 6])

# Calculate the dot product
dot_result = np.dot(vector_a, vector_b)

print(f"Dot Product: {dot_result}")

# Define two matrices for matrix multiplication
matrix_a = np.array([[1, 2, 3], [4, 5, 6]])
matrix_b = np.array([[7, 8], [9, 10], [11, 12]])

# Perform matrix multiplication
matmul_result = np.matmul(matrix_a, matrix_b)

print("Matrix Multiplication:")
print(matmul_result)

Dot Product: 41
Matrix Multiplication:
[[ 58  64]
 [139 154]]


## Iterate on an Array

In [2]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [3]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [4]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [5]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [6]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [7]:
for i in a2:
    for j in i:
        print(j)

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0


In [8]:
for i in a3:
    for j in i:
        for k in j:
            print(k)

0
1
2
3
4
5
6
7


In [9]:
for element in np.nditer(a3):
    print(element)

0
1
2
3
4
5
6
7


In [11]:
for element in np.ravel(a3):
    print(element)

0
1
2
3
4
5
6
7


In [13]:
for element in (a3.flat):
    print(element)

0
1
2
3
4
5
6
7


In [10]:
for element in np.nditer(a2):
    print(element)

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0


In [48]:
a10 = np.arange(12,24).reshape(3,4)

In [49]:
a10

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

    [12, 13, 14, 15], ->row 0
    [16, 17, 18, 19], ->row 1
    [20, 21, 22, 23]  ->row 2
      |   |   |   |
    col0 col1 col2 col3

In [52]:
# Accessing the first element
# a10[0:1,0:1]
a10[0,0]

12

In [53]:
# Accessing the 19 
a10[1,3]

19

In [54]:
# Accessing the 21
a10[2,1]


21

In [57]:
# Accessing multiple elements (13,14)
a10[0,1:3]



array([13, 14])

In [59]:
# Accessing multiple elements (17,18),(21,22)
a10


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [60]:
a10[1:,1:3]

array([[17, 18],
       [21, 22]])

## Stacking of an Array

In [17]:
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [20]:
a4,a5

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [21]:
np.vstack((a4,a5)) # column must be same

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
np.hstack((a4,a5)) # row must be same

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [25]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [30]:
np.hsplit(a5,2)

[array([[12, 13],
        [16, 17],
        [20, 21]]),
 array([[14, 15],
        [18, 19],
        [22, 23]])]

In [34]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

## Vector Operations

In [35]:
a4,a5

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [36]:
a4 * a5 

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [37]:
a3

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Broadcasting

* Must be Same sape
* dimension 1


In [41]:
a6= np.array([1,3,5,6])

In [42]:
a6

array([1, 3, 5, 6])

In [43]:
a3 * a6

array([[ 12,  39,  70,  90],
       [ 16,  51,  90, 114],
       [ 20,  63, 110, 138]])

In [46]:
# Modules  -> set of codes or simple function
# Packages -> set of modules
# Library -> set of packages

# all are Librabies
# numpy 
# pandas
# seaborn
# matplotlib
# scikit-learn